name: New Contributors - Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
            👋 Hello @${{ github.actor }}, thank you for your interest in Dinosaur Exploder 🦖! Please visit our ⭐️ Discord server if you need help about something.

            If this is a 🐛 Bug Report, please provide a **minimum reproducible example** to help us debug it.
            If this is a 🆕 feature request, please provide all your ideas, or better yet: a model of what you'd like to improve in the game. 
            
            - ✅ Verify that you have well fill out the different checkboxes in the issue template.
        pr-message: |
            👋 Hello @${{ github.actor }}, thank you for submitting in Dinosaur Exploder 🦖 PR! To allow your work to be integrated as seamlessly as possible, we advise you to:

            - ✅ Verify your PR is **up-to-date** with the repository `/dinosaur-exploder` `main` branch. If your PR is behind you can update your code by clicking the 'Update branch' button or by running `git pull` and `git merge master` locally.
            - ✅ Verify all Dinosaur Exploder Continuous Integration (CI) **checks are passing**.
            - ✅ Verify that you have well fill out the different checkboxes in the PR template.
            - ⚠️ Check that your code is clean: no code redundancy, variable and method names are correct, your code is understandable to everyone, and so on. 
            - 💡 Reduce changes to the absolute **minimum** required for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee
